/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;


import data.Settings.App_Settings;
import java.awt.CardLayout;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author mmmon
 */
public class Card_BS_PickABank extends javax.swing.JPanel {

    /**
     * Creates new form Card_BS_NewBank
     */
    
    private JFrame parentFrame;
    private JPanel parentPanel;
    private App_Settings appSettings;
    
    public Card_BS_PickABank() {
        
    }
    
    public void showCard(String [] banks, JPanel parentPanel, JFrame parentFrame){
        initComponents();
        this.parentFrame = parentFrame;
        this.parentPanel = parentPanel;
        cb_BankNames.setModel(new DefaultComboBoxModel(banks){});
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lbl_Description = new javax.swing.JLabel();
        lbl_BankNames = new javax.swing.JLabel();
        cb_BankNames = new presets.CM_ComboBox();
        btn_initSystem = new presets.CM_Button();
        btn_newBank = new presets.CM_Button();

        setMaximumSize(null);
        setMinimumSize(null);
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(487, 600));
        setLayout(new java.awt.GridBagLayout());

        lbl_Description.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_Description.setText("<html>\nPor favor selecciones el banco al que desea ingresar y haga click en el botón iniciar sistema.\n</html>");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 50;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        add(lbl_Description, gridBagConstraints);

        lbl_BankNames.setText("<html>Banco: </html>");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        add(lbl_BankNames, gridBagConstraints);

        cb_BankNames.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        cb_BankNames.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bank1", "Bank2" }));
        cb_BankNames.setMaximumSize(null);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        add(cb_BankNames, gridBagConstraints);

        btn_initSystem.setText("Iniciar sistema");
        btn_initSystem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_initSystemActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        add(btn_initSystem, gridBagConstraints);

        btn_newBank.setText("Registrar nuevo banco");
        btn_newBank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_newBankActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        add(btn_newBank, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_newBankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_newBankActionPerformed
        CardLayout cardlayout = (CardLayout)parentPanel.getLayout();
        cardlayout.show(parentPanel, "newBank");
    }//GEN-LAST:event_btn_newBankActionPerformed

    private void btn_initSystemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_initSystemActionPerformed
        
        W_Login login = new W_Login(appSettings);
        parentFrame.dispose();
        
    }//GEN-LAST:event_btn_initSystemActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private presets.CM_Button btn_initSystem;
    private presets.CM_Button btn_newBank;
    private presets.CM_ComboBox cb_BankNames;
    private javax.swing.JLabel lbl_BankNames;
    private javax.swing.JLabel lbl_Description;
    // End of variables declaration//GEN-END:variables
}
