/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import data.Settings.SQLite_DBManager;
import java.awt.CardLayout;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author mmmon
 */
public class Card_BS_NewBank extends javax.swing.JPanel {

    /**
     * Creates new form Card_BS_NewBank
     */
    JPanel parentPanel;
    W_BankSelector parentFrame;
    
    
    public Card_BS_NewBank() {
        
    }
    
    public void showCard(JPanel parentPanel, W_BankSelector parentFrame){
        this.parentPanel = parentPanel;
        this.parentFrame = parentFrame;
        initComponents();
        setVisible(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lbl_description = new javax.swing.JLabel();
        lbl_bankName = new javax.swing.JLabel();
        tf_bankName = new presets.CM_TextField();
        lbl_counters = new javax.swing.JLabel();
        cb_counters = new presets.CM_ComboBox();
        lbl_ticketDispensers = new javax.swing.JLabel();
        cb_dispensers = new presets.CM_ComboBox();
        jSeparator = new javax.swing.JSeparator();
        lbl_adminName = new javax.swing.JLabel();
        tf_adminName = new presets.CM_TextField();
        lbl_password = new javax.swing.JLabel();
        tf_password = new presets.CM_PasswordField();
        lbl_name = new javax.swing.JLabel();
        tf_name = new presets.CM_TextField();
        lbl_lastName = new javax.swing.JLabel();
        tf_lastName = new presets.CM_TextField();
        btn_newBank = new presets.CM_Button();
        filler_top = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        filler_bottom = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));

        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(470, 595));
        setLayout(new java.awt.GridBagLayout());

        lbl_description.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_description.setText("<html> No se han encontrado bancos registrados en el sistema.<br> Para continuar, por favor registre un banco y cree un usuario administrador para iniciar el sistema. </html>");
        lbl_description.setMaximumSize(null);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 50;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        add(lbl_description, gridBagConstraints);

        lbl_bankName.setText("Nombre del banco :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        add(lbl_bankName, gridBagConstraints);

        tf_bankName.setBorder(null);
        tf_bankName.setMaximumSize(null);
        tf_bankName.setMinimumSize(null);
        tf_bankName.setPreferredSize(null);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        add(tf_bankName, gridBagConstraints);

        lbl_counters.setText("<html>Cantidad <br>de cajas :</html>");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        add(lbl_counters, gridBagConstraints);

        cb_counters.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        cb_counters.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20" }));
        cb_counters.setMaximumSize(null);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        add(cb_counters, gridBagConstraints);

        lbl_ticketDispensers.setText("<html>Dispensadores <br>de tiquetes :</html>");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        add(lbl_ticketDispensers, gridBagConstraints);

        cb_dispensers.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        cb_dispensers.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20" }));
        cb_dispensers.setMaximumSize(null);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        add(cb_dispensers, gridBagConstraints);

        jSeparator.setMaximumSize(null);
        jSeparator.setMinimumSize(null);
        jSeparator.setPreferredSize(null);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        add(jSeparator, gridBagConstraints);

        lbl_adminName.setText("Nombre de usuario (Admin):");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        add(lbl_adminName, gridBagConstraints);

        tf_adminName.setBorder(null);
        tf_adminName.setMargin(new java.awt.Insets(20, 6, 2, 6));
        tf_adminName.setMaximumSize(null);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        add(tf_adminName, gridBagConstraints);

        lbl_password.setText("Contraseña: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        add(lbl_password, gridBagConstraints);

        tf_password.setBorder(null);
        tf_password.setMaximumSize(null);
        tf_password.setMinimumSize(null);
        tf_password.setPreferredSize(null);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        add(tf_password, gridBagConstraints);

        lbl_name.setText("Nombre");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        add(lbl_name, gridBagConstraints);

        tf_name.setBorder(null);
        tf_name.setMaximumSize(null);
        tf_name.setMinimumSize(null);
        tf_name.setPreferredSize(null);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        add(tf_name, gridBagConstraints);

        lbl_lastName.setText("Apellido");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        add(lbl_lastName, gridBagConstraints);

        tf_lastName.setBorder(null);
        tf_lastName.setMaximumSize(null);
        tf_lastName.setMinimumSize(null);
        tf_lastName.setPreferredSize(null);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        add(tf_lastName, gridBagConstraints);

        btn_newBank.setForeground(new java.awt.Color(255, 255, 255));
        btn_newBank.setText("Registrar banco");
        btn_newBank.setMaximumSize(new java.awt.Dimension(305, 40));
        btn_newBank.setMinimumSize(new java.awt.Dimension(105, 40));
        btn_newBank.setPreferredSize(null);
        btn_newBank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_newBankActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(40, 10, 0, 10);
        add(btn_newBank, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.2;
        add(filler_top, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.2;
        add(filler_bottom, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_newBankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_newBankActionPerformed
     
        if ( // Valida que los inputs sean correctos y no contengan SQL Injection
                parentFrame.getAppSettings().getSql().noSQLInjection(tf_bankName.getText())
                && !cb_counters.getSelectedItem().equals("0")
                && !cb_dispensers.getSelectedItem().equals("0")
                && parentFrame.getAppSettings().getSql().noSQLInjection(tf_adminName.getText())
                && parentFrame.getAppSettings().getSql().noSQLInjection(tf_password.getPWSD())
                && parentFrame.getAppSettings().getSql().noSQLInjection(tf_name.getText())
                && parentFrame.getAppSettings().getSql().noSQLInjection(tf_lastName.getText())) 
        {
            // Si cumple los criterios crea una nueva DB
            parentFrame.getAppSettings().getSql().createNewDB(
                    new String[]{
                        tf_bankName.getText(),
                        cb_counters.getSelectedItem() + "",
                        cb_dispensers.getSelectedItem() + ""
                    },
                    new String[]{
                        tf_adminName.getText(),
                        tf_password.getPWSD(),
                        tf_name.getText(),
                        tf_lastName.getText()
                    });
            
        }
        
        JOptionPane.showMessageDialog(getParent(),
                "El nuevo banco ha sido registrado exitosamente!!!", "Registro exitoso", JOptionPane.INFORMATION_MESSAGE);
        
        parentFrame.changeCard(2, parentFrame.getAppSettings().checkBankSites());
    }//GEN-LAST:event_btn_newBankActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private presets.CM_Button btn_newBank;
    private presets.CM_ComboBox cb_counters;
    private presets.CM_ComboBox cb_dispensers;
    private javax.swing.Box.Filler filler_bottom;
    private javax.swing.Box.Filler filler_top;
    private javax.swing.JSeparator jSeparator;
    private javax.swing.JLabel lbl_adminName;
    private javax.swing.JLabel lbl_bankName;
    private javax.swing.JLabel lbl_counters;
    private javax.swing.JLabel lbl_description;
    private javax.swing.JLabel lbl_lastName;
    private javax.swing.JLabel lbl_name;
    private javax.swing.JLabel lbl_password;
    private javax.swing.JLabel lbl_ticketDispensers;
    private presets.CM_TextField tf_adminName;
    private presets.CM_TextField tf_bankName;
    private presets.CM_TextField tf_lastName;
    private presets.CM_TextField tf_name;
    private presets.CM_PasswordField tf_password;
    // End of variables declaration//GEN-END:variables
}
