/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import data.Settings.App_Settings;
import java.awt.CardLayout;
import java.awt.GridBagConstraints;

/**
 * @author manuel.mora
 */
public class W_BankSelector extends javax.swing.JFrame {

    /**
     * Creates new form W_Login
     */
    
    private App_Settings appSettings;
    private GridBagConstraints gbc;
    
    public W_BankSelector(App_Settings appSettings) {
        
        this.appSettings = appSettings;
        setLocationRelativeTo(null);
        initComponents();
        checkBankSites();
        
        
        
        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new W_Login(appSettings).setVisible(true);
            }
        });
        
        
        pnl_StatusBar.showPanel(appSettings);
        pnl_Container.showPanel("bg3.png");
        
        repaint();
        revalidate();
        setVisible(true);
        
        
    }
    
    private void checkBankSites() {
        
        String [] sites = appSettings.checkBankSites();
        
        for (int i = 0; i < sites.length; i++) {
            sites[i] = sites[i].replace(".ped", "");
            sites[i] = sites[i].replace("_", " ");   
        }
        if (sites != null) {
            //cb_bankSelector.setModel(new javax.swing.DefaultComboBoxModel(sites));
            
            CardLayout cardLayout = (CardLayout) pnl_cards.getLayout();
            cardLayout.show(pnl_cards, "Card1");
        }
        
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnl_StatusBar = new presets.Pnl_StatusBar();
        pnl_Container = new presets.Custom_Panel();
        p_container = new javax.swing.JPanel();
        lbl_Title = new javax.swing.JLabel();
        pnl_cards = new javax.swing.JPanel();
        pnl_newSite = new javax.swing.JPanel();
        lbl_Description = new javax.swing.JLabel();
        lbl_BankName = new javax.swing.JLabel();
        tf_BankName = new presets.Custom_TextField();
        lbl_Counters = new javax.swing.JLabel();
        cb_Counters = new presets.Custom_ComboBox();
        lbl_TicketDispensers = new javax.swing.JLabel();
        cb_Dispensers = new presets.Custom_ComboBox();
        jSeparator = new javax.swing.JSeparator();
        lbl_AdminName = new javax.swing.JLabel();
        tf_AdminName = new presets.Custom_TextField();
        lbl_Password = new javax.swing.JLabel();
        tf_Password = new presets.Custom_PasswordField();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de registro");
        setMaximumSize(null);
        setName("Login"); // NOI18N
        setResizable(false);
        setSize(new java.awt.Dimension(0, 0));
        setType(java.awt.Window.Type.UTILITY);

        pnl_StatusBar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnl_StatusBar.setMaximumSize(null);
        pnl_StatusBar.setMinimumSize(null);
        pnl_StatusBar.setPreferredSize(new java.awt.Dimension(975, 25));
        getContentPane().add(pnl_StatusBar, java.awt.BorderLayout.SOUTH);

        pnl_Container.setPreferredSize(new java.awt.Dimension(975, 525));
        pnl_Container.setLayout(new java.awt.BorderLayout());

        p_container.setOpaque(false);
        p_container.setPreferredSize(new java.awt.Dimension(485, 575));
        p_container.setLayout(new java.awt.BorderLayout());

        lbl_Title.setFont(new java.awt.Font("Candara", 1, 24)); // NOI18N
        lbl_Title.setForeground(new java.awt.Color(0, 204, 204));
        lbl_Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Title.setText("Bienvenido a nuestro sistema");
        lbl_Title.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbl_Title.setPreferredSize(new java.awt.Dimension(500, 50));
        p_container.add(lbl_Title, java.awt.BorderLayout.PAGE_START);

        pnl_cards.setOpaque(false);
        pnl_cards.setPreferredSize(new java.awt.Dimension(485, 525));
        pnl_cards.setLayout(new java.awt.CardLayout());

        pnl_newSite.setOpaque(false);
        pnl_newSite.setPreferredSize(new java.awt.Dimension(500, 525));
        pnl_newSite.setLayout(new java.awt.GridBagLayout());

        lbl_Description.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_Description.setText("<html> No se han encontrado bancos registrados en el sistema.<br> Para continuar, por favor registre un banco y cree un usuario administrador. </html>");
        lbl_Description.setMaximumSize(null);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 50;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        pnl_newSite.add(lbl_Description, gridBagConstraints);

        lbl_BankName.setText("Nombre del banco :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        pnl_newSite.add(lbl_BankName, gridBagConstraints);

        tf_BankName.setBorder(null);
        tf_BankName.setMaximumSize(null);
        tf_BankName.setMinimumSize(null);
        tf_BankName.setPreferredSize(null);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        pnl_newSite.add(tf_BankName, gridBagConstraints);

        lbl_Counters.setText("<html>Cantidad <br>de cajas :</html>");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        pnl_newSite.add(lbl_Counters, gridBagConstraints);

        cb_Counters.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        cb_Counters.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20" }));
        cb_Counters.setMaximumSize(null);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        pnl_newSite.add(cb_Counters, gridBagConstraints);

        lbl_TicketDispensers.setText("<html>Dispensadores <br>de tiquetes :</html>");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        pnl_newSite.add(lbl_TicketDispensers, gridBagConstraints);

        cb_Dispensers.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        cb_Dispensers.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20" }));
        cb_Dispensers.setMaximumSize(null);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        pnl_newSite.add(cb_Dispensers, gridBagConstraints);

        jSeparator.setMaximumSize(null);
        jSeparator.setMinimumSize(null);
        jSeparator.setPreferredSize(null);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        pnl_newSite.add(jSeparator, gridBagConstraints);

        lbl_AdminName.setText("Nombre de usuario (Admin):");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        pnl_newSite.add(lbl_AdminName, gridBagConstraints);

        tf_AdminName.setBorder(null);
        tf_AdminName.setMaximumSize(null);
        tf_AdminName.setMinimumSize(null);
        tf_AdminName.setPreferredSize(null);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        pnl_newSite.add(tf_AdminName, gridBagConstraints);

        lbl_Password.setText("Contraseña: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        pnl_newSite.add(lbl_Password, gridBagConstraints);

        tf_Password.setBorder(null);
        tf_Password.setMaximumSize(null);
        tf_Password.setMinimumSize(null);
        tf_Password.setPreferredSize(null);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        pnl_newSite.add(tf_Password, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 30, 50, 30);
        pnl_newSite.add(filler1, gridBagConstraints);

        pnl_cards.add(pnl_newSite, "Card1");

        p_container.add(pnl_cards, java.awt.BorderLayout.CENTER);

        pnl_Container.add(p_container, java.awt.BorderLayout.EAST);

        getContentPane().add(pnl_Container, java.awt.BorderLayout.NORTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private presets.Custom_ComboBox cb_Counters;
    private presets.Custom_ComboBox cb_Dispensers;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JSeparator jSeparator;
    private javax.swing.JLabel lbl_AdminName;
    private javax.swing.JLabel lbl_BankName;
    private javax.swing.JLabel lbl_Counters;
    private javax.swing.JLabel lbl_Description;
    private javax.swing.JLabel lbl_Password;
    private javax.swing.JLabel lbl_TicketDispensers;
    private javax.swing.JLabel lbl_Title;
    private javax.swing.JPanel p_container;
    private presets.Custom_Panel pnl_Container;
    private presets.Pnl_StatusBar pnl_StatusBar;
    private javax.swing.JPanel pnl_cards;
    private javax.swing.JPanel pnl_newSite;
    private presets.Custom_TextField tf_AdminName;
    private presets.Custom_TextField tf_BankName;
    private presets.Custom_PasswordField tf_Password;
    // End of variables declaration//GEN-END:variables

    
}
