/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import data.Settings.App_Settings;
import java.awt.GridBagConstraints;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 * @author manuel.mora
 */
public class W_BankSelector extends javax.swing.JFrame {

    /**
     * Creates new form W_Login
     */
    
    private App_Settings appSettings;
    private GridBagConstraints gbc;
    private Card_BS_NewBank card_NewBank;
    private Card_BS_PickABank card_PickABank;
    
    public W_BankSelector(App_Settings appSettings) {
        
        this.appSettings = appSettings;
        
        initComponents();
        
        pnl_StatusBar.showPanel(appSettings);
        pnl_Main.showPanel("bg2.png");
        
        checkBankSites();
        setLocationRelativeTo(null);
        
        repaint();
        revalidate();
        
        
        
    }
    
    private void checkBankSites() {
        
        setVisible(true);
        
        // Verifica si existen Db para bancos
        String [] sites = appSettings.checkBankSites();
        
        pnl_cards.add(new JLabel(""));
        
        if (sites == null) { // Si no encuentra muestra ventana de nuevo banco
            changeCard(1, null);
        }else if (0 < sites.length) { // Si encuentra muestra el selector de bancos
            changeCard(2, sites);
        }
        
    }
    
    public void changeCard(int cardID, String [] sites){
        p_container.removeAll();
        switch (cardID) {
            case 1:
                card_NewBank = new Card_BS_NewBank();
                card_NewBank.showCard(p_container, this);
                p_container.add(card_NewBank, "Center");
                break;
            case 2:
                card_PickABank = new Card_BS_PickABank();
                card_PickABank.showCard(sites, pnl_cards, this);
                p_container.add(card_PickABank, "Center");
                break;
        }
        revalidate();
        repaint();
    }

    public App_Settings getAppSettings() {
        return appSettings;
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_StatusBar = new presets.CM_StatusBar();
        pnl_Main = new presets.CM_Panel();
        p_container12 = new javax.swing.JScrollPane();
        p_container = new javax.swing.JPanel();
        lbl_Title = new javax.swing.JLabel();
        pnl_cards = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de registro");
        setMaximumSize(null);
        setName("Login"); // NOI18N
        setResizable(false);
        setSize(new java.awt.Dimension(0, 0));
        setType(java.awt.Window.Type.UTILITY);

        pnl_StatusBar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnl_StatusBar.setMaximumSize(null);
        pnl_StatusBar.setMinimumSize(null);
        pnl_StatusBar.setPreferredSize(new java.awt.Dimension(975, 25));
        getContentPane().add(pnl_StatusBar, java.awt.BorderLayout.SOUTH);

        pnl_Main.setPreferredSize(new java.awt.Dimension(485, 605));
        pnl_Main.setLayout(new java.awt.BorderLayout());

        p_container12.setMaximumSize(null);
        p_container12.setMinimumSize(null);
        p_container12.setPreferredSize(new java.awt.Dimension(485, 595));
        pnl_Main.add(p_container12, java.awt.BorderLayout.EAST);

        p_container.setPreferredSize(new java.awt.Dimension(485, 605));
        p_container.setLayout(new java.awt.BorderLayout());

        lbl_Title.setFont(new java.awt.Font("Candara", 1, 24)); // NOI18N
        lbl_Title.setForeground(new java.awt.Color(0, 204, 204));
        lbl_Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Title.setText("Bienvenido a nuestro sistema");
        lbl_Title.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbl_Title.setPreferredSize(new java.awt.Dimension(500, 50));
        p_container.add(lbl_Title, java.awt.BorderLayout.NORTH);

        pnl_cards.setOpaque(false);
        pnl_cards.setPreferredSize(new java.awt.Dimension(485, 595));
        pnl_cards.setLayout(new java.awt.BorderLayout());
        p_container.add(pnl_cards, java.awt.BorderLayout.CENTER);

        pnl_Main.add(p_container, java.awt.BorderLayout.EAST);

        getContentPane().add(pnl_Main, java.awt.BorderLayout.NORTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbl_Title;
    private javax.swing.JPanel p_container;
    private javax.swing.JScrollPane p_container12;
    private presets.CM_Panel pnl_Main;
    private presets.CM_StatusBar pnl_StatusBar;
    private javax.swing.JPanel pnl_cards;
    // End of variables declaration//GEN-END:variables

    
}
