/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import data.Settings.App_Settings;
import java.awt.GridBagConstraints;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 * @author manuel.mora
 */
public class W_BankSelector extends javax.swing.JFrame {

    /**
     * Creates new form W_Login
     */
    
    private App_Settings appSettings;
    private GridBagConstraints gbc;
    private Card_BS_NewBank card_NewBank;
    private Card_BS_PickABank card_PickABank;
    
    public W_BankSelector(App_Settings appSettings) {
        
        this.appSettings = appSettings;
        setLocationRelativeTo(null);
        
        initComponents();
        
        pnl_StatusBar.showPanel(appSettings);
        pnl_Container.showPanel("bg2.png");
        
        checkBankSites();
        
        
        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new W_Login(appSettings).setVisible(true);
            }
        });*/
        
        
        
        repaint();
        revalidate();
        
        
        
    }
    
    private void checkBankSites() {
        
        setVisible(true);
        
        // Verifica si existen Db para bancos
        String [] sites = appSettings.checkBankSites();
        
        /*for (int i = 0; i < 10; i++) {
            try {
                cardLayout.show(pnl_cards, "newBank");
                revalidate(); repaint();
                TimeUnit.SECONDS.sleep(1);
                cardLayout.show(pnl_cards, "pickABank");
                revalidate(); repaint();
            } catch (InterruptedException ex) {
                Logger.getLogger(W_BankSelector.class.getName()).log(Level.SEVERE, null, ex);
            }
        }*/
        pnl_cards.add(new JLabel(""));
        
        
        if (sites == null) { // Si no encuentra muestra ventana de nuevo banco
            
            card_NewBank = new Card_BS_NewBank();
            card_NewBank.showCard(pnl_cards);
            changeCard(card_NewBank);
        }else if (0 < sites.length) { // Si encuentra muestra el selector de bancos
            card_PickABank = new Card_BS_PickABank();
            card_PickABank.showCard(sites, pnl_cards, this);
            changeCard(card_PickABank);
        }
        
    }
    
    public void changeCard(JPanel card){
        pnl_cards.remove(1);
        pnl_cards.add(card);
        revalidate(); repaint();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_StatusBar = new presets.CM_StatusBar();
        pnl_Container = new presets.CM_Panel();
        p_container = new javax.swing.JScrollPane();
        pnl_cards = new javax.swing.JPanel();
        lbl_Title = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de registro");
        setMaximumSize(null);
        setName("Login"); // NOI18N
        setSize(new java.awt.Dimension(0, 0));
        setType(java.awt.Window.Type.UTILITY);

        pnl_StatusBar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnl_StatusBar.setMaximumSize(null);
        pnl_StatusBar.setMinimumSize(null);
        pnl_StatusBar.setPreferredSize(new java.awt.Dimension(975, 25));
        getContentPane().add(pnl_StatusBar, java.awt.BorderLayout.SOUTH);

        pnl_Container.setPreferredSize(new java.awt.Dimension(485, 600));
        pnl_Container.setLayout(new java.awt.BorderLayout());

        p_container.setMaximumSize(null);
        p_container.setMinimumSize(null);
        p_container.setPreferredSize(new java.awt.Dimension(485, 595));

        pnl_cards.setOpaque(false);
        pnl_cards.setPreferredSize(new java.awt.Dimension(485, 595));
        pnl_cards.setLayout(new java.awt.BorderLayout());

        lbl_Title.setFont(new java.awt.Font("Candara", 1, 24)); // NOI18N
        lbl_Title.setForeground(new java.awt.Color(0, 204, 204));
        lbl_Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Title.setText("Bienvenido a nuestro sistema");
        lbl_Title.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbl_Title.setPreferredSize(new java.awt.Dimension(500, 50));
        pnl_cards.add(lbl_Title, java.awt.BorderLayout.PAGE_START);

        p_container.setViewportView(pnl_cards);

        pnl_Container.add(p_container, java.awt.BorderLayout.EAST);

        getContentPane().add(pnl_Container, java.awt.BorderLayout.NORTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbl_Title;
    private javax.swing.JScrollPane p_container;
    private presets.CM_Panel pnl_Container;
    private presets.CM_StatusBar pnl_StatusBar;
    private javax.swing.JPanel pnl_cards;
    // End of variables declaration//GEN-END:variables

    
}
