/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import data.InfoObjetcs.Ticket;
import data.Settings.App_Settings;
import java.awt.GridBagConstraints;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Date;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import presets.CM_Button;

/**
 * @author manuel.mora
 */
public class W_Home extends javax.swing.JFrame {

    /**
     * Creates new form W_Login
     */
    
    private App_Settings appSettings;
    
    public W_Home(App_Settings appSettings) {
        
        this.appSettings = appSettings;
        
        initComponents();
        
        pnl_StatusBar.showPanel(appSettings);
        pnl_Main.showPanel("bg1.png");
        
        lbl_Title.setText(lbl_Title.getText().replace("###", appSettings.getCurrentUser().getName()));
        
        setVisible(true);
        setLocationRelativeTo(null);
        
        repaint();
        revalidate();
        
        
        
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnl_StatusBar = new presets.CM_StatusBar();
        pnl_Main = new presets.CM_Panel();
        p_container = new javax.swing.JPanel();
        lbl_Title = new javax.swing.JLabel();
        btn_createTicket = new presets.CM_Button();
        btn_Queue = new presets.CM_Button();
        btn_processTicket = new presets.CM_Button();
        btn_reports = new presets.CM_Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de registro");
        setName("Login"); // NOI18N
        setResizable(false);
        setSize(new java.awt.Dimension(0, 0));
        setType(java.awt.Window.Type.UTILITY);

        pnl_StatusBar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnl_StatusBar.setMaximumSize(null);
        pnl_StatusBar.setMinimumSize(null);
        pnl_StatusBar.setPreferredSize(new java.awt.Dimension(975, 25));
        getContentPane().add(pnl_StatusBar, java.awt.BorderLayout.SOUTH);

        pnl_Main.setPreferredSize(new java.awt.Dimension(485, 605));
        pnl_Main.setLayout(new java.awt.BorderLayout());

        p_container.setMaximumSize(null);
        p_container.setOpaque(false);
        p_container.setPreferredSize(null);
        p_container.setLayout(new java.awt.GridBagLayout());

        lbl_Title.setFont(new java.awt.Font("Candara", 1, 36)); // NOI18N
        lbl_Title.setForeground(new java.awt.Color(0, 204, 204));
        lbl_Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Title.setText("Hola ###, ¿Que deseas hacer?");
        lbl_Title.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbl_Title.setPreferredSize(new java.awt.Dimension(500, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        p_container.add(lbl_Title, gridBagConstraints);

        btn_createTicket.setForeground(new java.awt.Color(255, 255, 255));
        btn_createTicket.setText("Dispensar tiquetes");
        btn_createTicket.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btn_createTicket.setMargin(new java.awt.Insets(10, 10, 10, 10));
        btn_createTicket.setPreferredSize(new java.awt.Dimension(200, 100));
        btn_createTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_createTicketActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.ipady = 50;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        p_container.add(btn_createTicket, gridBagConstraints);

        btn_Queue.setForeground(new java.awt.Color(255, 255, 255));
        btn_Queue.setText("Ver cola de cajas");
        btn_Queue.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btn_Queue.setMargin(new java.awt.Insets(10, 10, 10, 10));
        btn_Queue.setPreferredSize(new java.awt.Dimension(200, 100));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.ipady = 50;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        p_container.add(btn_Queue, gridBagConstraints);

        btn_processTicket.setForeground(new java.awt.Color(255, 255, 255));
        btn_processTicket.setText("Tramitar tiquete");
        btn_processTicket.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btn_processTicket.setMargin(new java.awt.Insets(10, 10, 10, 10));
        btn_processTicket.setPreferredSize(new java.awt.Dimension(200, 100));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.ipady = 50;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        p_container.add(btn_processTicket, gridBagConstraints);

        btn_reports.setForeground(new java.awt.Color(255, 255, 255));
        btn_reports.setText("Reportes");
        btn_reports.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btn_reports.setMargin(new java.awt.Insets(10, 10, 10, 10));
        btn_reports.setPreferredSize(new java.awt.Dimension(200, 100));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.ipady = 50;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        p_container.add(btn_reports, gridBagConstraints);

        pnl_Main.add(p_container, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnl_Main, java.awt.BorderLayout.NORTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_createTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_createTicketActionPerformed
        W_Dispenser wp = new W_Dispenser(appSettings);
    }//GEN-LAST:event_btn_createTicketActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private presets.CM_Button btn_Queue;
    private presets.CM_Button btn_createTicket;
    private presets.CM_Button btn_processTicket;
    private presets.CM_Button btn_reports;
    private javax.swing.JLabel lbl_Title;
    private javax.swing.JPanel p_container;
    private presets.CM_Panel pnl_Main;
    private presets.CM_StatusBar pnl_StatusBar;
    // End of variables declaration//GEN-END:variables

    
}
